#!/bin/bash
NAME="BUSYCENT"
VERSION="1.0.0"
BREADCUM="MAIN MENU"
DIR=$(dirname $0)

. ${DIR}/libs/gui.sh

createMainMenu(){
	echo "1. Server Information";
	echo "2. Testing Tools"; 
	echo "3. LEMP Tools"; 
	echo "4. LAMP Tools";
	echo "5. VCS Tools";
	echo "9. Security Tools";
	
}

option_1(){
	sh ${DIR}/busyinfo.sh;
}

option_2(){
	sh ${DIR}/busytest.sh;	
}

option_3(){
	sh ${DIR}/busylemp.sh;
}

option_4(){
	sh ${DIR}/busylamp.sh;
}

option_4(){
	sh ${DIR}/busyvcs.sh;
}

option_9(){
	sh ${DIR}/busysecurity.sh;	
}



_run
